spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    dispatch-options-request: true
#  thymeleaf:
#    cache: false
server:
  port: 8081